-- =====================================================
-- VYRA Oracle Test Schema — Is Modeli
-- Telekom/Perakende senaryosu
-- =====================================================
-- gvenzl initdb.d scriptleri "/ AS SYSDBA" (SYS, CDB$ROOT) baglaminda kosar
-- (container-entrypoint.sh:246); bu yuzden objeler yanlislikla SYS@CDB-root'a
-- dusuyordu. Asagidaki ALTER SESSION ile dogru hedef: VYRA_TEST semasi @ FREEPDB1.
-- Manuel: sqlplus VYRA_TEST/VyraTest2026@localhost:1521/FREEPDB1 @01_create_schema.sql
-- =====================================================
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = VYRA_TEST;

-- ── Musteriler ──
CREATE TABLE MUSTERILER (
    MUSTERI_ID       NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AD               VARCHAR2(50)     NOT NULL,
    SOYAD            VARCHAR2(50)     NOT NULL,
    TC_KIMLIK        VARCHAR2(11)     UNIQUE,
    EMAIL            VARCHAR2(100),
    TELEFON          VARCHAR2(20),
    DOGUM_TARIHI     DATE,
    CINSIYET         VARCHAR2(1)      CHECK (CINSIYET IN ('E', 'K')),
    SEGMENT          VARCHAR2(30)     DEFAULT 'Bireysel',
    KAYIT_TARIHI     DATE             DEFAULT SYSDATE NOT NULL,
    AKTIF_MI         NUMBER(1)        DEFAULT 1 CHECK (AKTIF_MI IN (0, 1))
);

-- ── Adresler ──
CREATE TABLE ADRESLER (
    ADRES_ID         NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MUSTERI_ID       NUMBER(10)       NOT NULL REFERENCES MUSTERILER(MUSTERI_ID),
    ADRES_TIPI       VARCHAR2(20)     DEFAULT 'EV' CHECK (ADRES_TIPI IN ('EV', 'IS', 'FATURA', 'TESLIMAT')),
    IL               VARCHAR2(30)     NOT NULL,
    ILCE             VARCHAR2(30),
    MAHALLE          VARCHAR2(60),
    ADRES_DETAY      VARCHAR2(200),
    POSTA_KODU       VARCHAR2(10)
);

-- ── Urun Kategorileri ──
CREATE TABLE URUN_KATEGORILERI (
    KATEGORI_ID      NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    KATEGORI_ADI     VARCHAR2(60)     NOT NULL UNIQUE,
    UST_KATEGORI_ID  NUMBER(10)       REFERENCES URUN_KATEGORILERI(KATEGORI_ID),
    ACIKLAMA         VARCHAR2(200)
);

-- ── Urunler ──
CREATE TABLE URUNLER (
    URUN_ID          NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    URUN_KODU        VARCHAR2(30)     NOT NULL UNIQUE,
    URUN_ADI         VARCHAR2(120)    NOT NULL,
    KATEGORI_ID      NUMBER(10)       REFERENCES URUN_KATEGORILERI(KATEGORI_ID),
    BIRIM_FIYAT      NUMBER(12,2)     NOT NULL,
    KDV_ORANI        NUMBER(4,2)      DEFAULT 20.00,
    STOK_MIKTARI     NUMBER(10)       DEFAULT 0,
    BIRIM            VARCHAR2(20)     DEFAULT 'ADET',
    AKTIF_MI         NUMBER(1)        DEFAULT 1,
    OLUSTURMA_TARIHI DATE             DEFAULT SYSDATE
);

-- ── Siparisler ──
CREATE TABLE SIPARISLER (
    SIPARIS_ID       NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MUSTERI_ID       NUMBER(10)       NOT NULL REFERENCES MUSTERILER(MUSTERI_ID),
    SIPARIS_TARIHI   DATE             DEFAULT SYSDATE NOT NULL,
    TESLIM_TARIHI    DATE,
    DURUM            VARCHAR2(20)     DEFAULT 'BEKLEMEDE' CHECK (DURUM IN ('BEKLEMEDE','HAZIRLANIYOR','KARGODA','TESLIM_EDILDI','IPTAL')),
    TOPLAM_TUTAR     NUMBER(14,2),
    KDV_TUTAR        NUMBER(14,2),
    INDIRIM_TUTAR    NUMBER(14,2)     DEFAULT 0,
    TESLIMAT_ADRES_ID NUMBER(10)      REFERENCES ADRESLER(ADRES_ID),
    NOTLAR           VARCHAR2(500)
);

-- ── Siparis Detay ──
CREATE TABLE SIPARIS_DETAY (
    DETAY_ID         NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SIPARIS_ID       NUMBER(10)       NOT NULL REFERENCES SIPARISLER(SIPARIS_ID),
    URUN_ID          NUMBER(10)       NOT NULL REFERENCES URUNLER(URUN_ID),
    MIKTAR           NUMBER(10)       NOT NULL CHECK (MIKTAR > 0),
    BIRIM_FIYAT      NUMBER(12,2)     NOT NULL,
    INDIRIM_ORANI    NUMBER(5,2)      DEFAULT 0,
    SATIR_TUTAR      NUMBER(14,2)     NOT NULL
);

-- ── Faturalar ──
CREATE TABLE FATURALAR (
    FATURA_ID        NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SIPARIS_ID       NUMBER(10)       NOT NULL REFERENCES SIPARISLER(SIPARIS_ID),
    FATURA_NO        VARCHAR2(30)     NOT NULL UNIQUE,
    FATURA_TARIHI    DATE             DEFAULT SYSDATE NOT NULL,
    FATURA_TIPI      VARCHAR2(20)     DEFAULT 'SATIS' CHECK (FATURA_TIPI IN ('SATIS', 'IADE', 'PROFORMA')),
    ARA_TOPLAM       NUMBER(14,2)     NOT NULL,
    KDV_TUTAR        NUMBER(14,2)     NOT NULL,
    TOPLAM_TUTAR     NUMBER(14,2)     NOT NULL,
    ODEME_DURUMU     VARCHAR2(20)     DEFAULT 'ODENMEDI' CHECK (ODEME_DURUMU IN ('ODENMEDI','KISMEN_ODENDI','ODENDI')),
    VADE_TARIHI      DATE
);

-- ── Odemeler ──
CREATE TABLE ODEMELER (
    ODEME_ID         NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FATURA_ID        NUMBER(10)       NOT NULL REFERENCES FATURALAR(FATURA_ID),
    ODEME_TARIHI     DATE             DEFAULT SYSDATE NOT NULL,
    ODEME_TUTARI     NUMBER(14,2)     NOT NULL,
    ODEME_YONTEMI    VARCHAR2(30)     NOT NULL CHECK (ODEME_YONTEMI IN ('NAKIT','KREDI_KARTI','HAVALE','EFT','CEK','TAKSIT')),
    REFERANS_NO      VARCHAR2(50),
    BANKA_ADI        VARCHAR2(60),
    DURUM            VARCHAR2(20)     DEFAULT 'BASARILI' CHECK (DURUM IN ('BASARILI','BASARISIZ','BEKLEMEDE','IADE'))
);

-- ── Abonelikler (Telekom modeli) ──
CREATE TABLE ABONELIKLER (
    ABONELIK_ID      NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MUSTERI_ID       NUMBER(10)       NOT NULL REFERENCES MUSTERILER(MUSTERI_ID),
    TARIFE_ADI       VARCHAR2(80)     NOT NULL,
    ABONELIK_TIPI    VARCHAR2(30)     CHECK (ABONELIK_TIPI IN ('MOBIL','FIBER','TV','KOMBI')),
    BASLANGIC_TARIHI DATE             NOT NULL,
    BITIS_TARIHI     DATE,
    AYLIK_TUTAR      NUMBER(12,2)     NOT NULL,
    DURUM            VARCHAR2(20)     DEFAULT 'AKTIF' CHECK (DURUM IN ('AKTIF','DONDURULDU','IPTAL','SURESI_DOLDU')),
    HAT_NUMARASI     VARCHAR2(20),
    TAAHHUT_AY       NUMBER(3)        DEFAULT 0
);

-- ── Destek Talepleri ──
CREATE TABLE DESTEK_TALEPLERI (
    TALEP_ID         NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MUSTERI_ID       NUMBER(10)       NOT NULL REFERENCES MUSTERILER(MUSTERI_ID),
    ABONELIK_ID      NUMBER(10)       REFERENCES ABONELIKLER(ABONELIK_ID),
    TALEP_TARIHI     DATE             DEFAULT SYSDATE NOT NULL,
    KATEGORI         VARCHAR2(40)     NOT NULL,
    ONCELIK          VARCHAR2(10)     DEFAULT 'NORMAL' CHECK (ONCELIK IN ('DUSUK','NORMAL','YUKSEK','KRITIK')),
    DURUM            VARCHAR2(20)     DEFAULT 'ACIK' CHECK (DURUM IN ('ACIK','ISLEMDE','BEKLEMEDE','COZULDU','KAPATILDI')),
    ACIKLAMA         VARCHAR2(1000),
    COZUM_TARIHI     DATE,
    COZUM_NOTU       VARCHAR2(500)
);

-- ── Kampanyalar ──
CREATE TABLE KAMPANYALAR (
    KAMPANYA_ID      NUMBER(10)       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    KAMPANYA_ADI     VARCHAR2(120)    NOT NULL,
    BASLANGIC_TARIHI DATE             NOT NULL,
    BITIS_TARIHI     DATE             NOT NULL,
    INDIRIM_ORANI    NUMBER(5,2),
    INDIRIM_TUTAR    NUMBER(12,2),
    MIN_SIPARIS_TUTAR NUMBER(12,2)    DEFAULT 0,
    AKTIF_MI         NUMBER(1)        DEFAULT 1,
    ACIKLAMA         VARCHAR2(300)
);

-- ── Indexler (performans) ──
CREATE INDEX IDX_ADRESLER_MUSTERI ON ADRESLER(MUSTERI_ID);
CREATE INDEX IDX_SIPARISLER_MUSTERI ON SIPARISLER(MUSTERI_ID);
CREATE INDEX IDX_SIPARISLER_TARIH ON SIPARISLER(SIPARIS_TARIHI);
CREATE INDEX IDX_SIPARIS_DETAY_SIPARIS ON SIPARIS_DETAY(SIPARIS_ID);
CREATE INDEX IDX_SIPARIS_DETAY_URUN ON SIPARIS_DETAY(URUN_ID);
CREATE INDEX IDX_FATURALAR_SIPARIS ON FATURALAR(SIPARIS_ID);
CREATE INDEX IDX_ODEMELER_FATURA ON ODEMELER(FATURA_ID);
CREATE INDEX IDX_ABONELIKLER_MUSTERI ON ABONELIKLER(MUSTERI_ID);
CREATE INDEX IDX_DESTEK_MUSTERI ON DESTEK_TALEPLERI(MUSTERI_ID);
CREATE INDEX IDX_DESTEK_ABONELIK ON DESTEK_TALEPLERI(ABONELIK_ID);
